name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      - name: UP
        run: docker-compose up -d
      - uses: juliangruber/sleep-action@v1
        with:
            time: 60s
      - name: docker ls
        run: docker container ls
      - name: curl
        run: curl http://localhost:8080
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with Maven
        run: mvn -B package --file pom.xml test
          
        
      
