name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  wget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Management
        run: |
          wget "https://download.hazelcast.com/management-center/hazelcast-management-center-4.2021.04.zip" -O
          ls -la
          echo "Root Directory"
          cd /usr/local/bin/
          ls -la /usr/local/bin/
          echo "Docs Root Directory"


  test_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with Maven
        run: mvn clean test

  test_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with Maven
        run: mvn -B package --file pom.xml test
