name: Hazelcast
on: push
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Buradayim
      run: ls -a
      
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Buradayim2
      run: ls -a

    - name: Start containers
      run: docker-compose -f ".github/workflows/docker-compose.yml" up -d --build
      
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - uses: juliangruber/sleep-action@v1
      with:
          time: 60s
    - name: Test with Maven
      run:  docker container ls -a && curl http://0.0.0.0:8080 && mvn -B package --file pom.xml test
