name: Hazelcast
on: push
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "./docker-compose.yml" up -d --build
      
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - uses: juliangruber/sleep-action@v1
      with:
          time: 60s
    - name: Test with Maven
      run:  docker container ls -a && ps aux && mvn -B package --file pom.xml test
