name: Hazelcast
on: push
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

    - name: buradayim main
      run: pwd && ls -a

    - uses: actions/checkout@v1
    - uses: ./action
    
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - uses: juliangruber/sleep-action@v1
      with:
          time: 60s
    - name: Test with Maven
      run:  docker container ls -a && curl http://0.0.0.0:8080 && mvn -B package --file pom.xml test
