name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: bjk
        run: pwd & ls -l
        
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
        
      - name: UP
        run: docker-compose up -d
      - uses: juliangruber/sleep-action@v1
        with:
          time: 60s

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - uses: actions/checkout@v2
      - name: Test with Maven
        run: mvn -B package --file pom.xml test
      
      - name: deneme
        if: ${{ always() }}
        run: |
          echo hello > ~/world.txt
          pwd
          ls -l
      
        
      - name: copy file
        if: ${{ always() }}
        uses: canastro/copy-file-action@master
        with:
         source: "~/screen/fail.png"
         target: "~/fail.png"
      
      - name: ls
        if: ${{ always() }}
        run: pwd & ls -l
      
      - uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
         name: my-artifact
         path: ~/world.txt
          
      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: shot
          path: ~/screen/fail.png
